FROM osrf/ros:kilted-desktop-full

# Arguments for building
ARG USERID
ARG USER

# Setup environment
ENV TERM=linux
ENV DEBIAN_FRONTEND=noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Copy requirement files and install dependencies
COPY docker/requirements.txt .
RUN apt-get update && apt-get install --no-install-recommends -y $(cat requirements.txt) && rm -rf /var/lib/apt/lists/*
RUN rm requirements.txt

# Install Gazebo Ionic
# RUN sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
# RUN wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
# RUN sudo apt-get update
# RUN sudo apt-get install gz-ionic -y

# Create a user with passwordless sudo
RUN adduser --gecos "admin" --disabled-password $USER
RUN adduser $USER sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers



USER $USER


####################### GITS
RUN mkdir -p /home/$USER/ros_ws/src
WORKDIR /home/$USER/ros_ws/src
RUN git clone https://github.com/b-robotized/ads_vendor.git
RUN git clone https://github.com/b-robotized/beckhoff_ads_driver.git
RUN git clone https://github.com/orka375/tc_ros2_itf.git

# RUN rosdep update
RUN git clone https://github.com/b-robotized/open62541pp_vendor.git
RUN git clone https://github.com/b-robotized/ros2_opc_ua.git

WORKDIR /home/$USER/ros_ws/
# RUN . /opt/ros/kilted/setup.sh && rosdep install -y -i --from-paths src



####################### Update
# RUN sudo apt upgrade -y && sudo apt update



RUN . /opt/ros/kilted/setup.sh && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
# Adds overlay to the bashrc
RUN echo "source /home/$USER/ros_ws/install/setup.bash" >> /home/$USER/.bashrc

######################
# Bashrc configuration
######################

# Adds to bashrc the ros kilted overlay sourcing.
RUN echo "source /opt/ros/kilted/setup.bash" >> /home/$USER/.bashrc
# Adds colcon autocomplete
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /home/$USER/.bashrc
RUN echo "export ROS_DOMAIN_ID=1" >> /home/$USER/.bashrc
RUN echo "export QT_X11_NO_MITSHM=1" >> /home/$USER/.bashrc
RUN echo "export IGN_IP=127.0.0.1" >> /home/$USER/.bashrc
RUN echo "cd /home/$USER/ros_ws/src/tc_ros2_itf" >> /home/$USER/.bashrc
RUN echo "git pull" >> /home/$USER/.bashrc
RUN echo "cd .." >> /home/$USER/.bashrc
RUN echo "cd .." >> /home/$USER/.bashrc

#########################
# Pip installation setup
#########################
RUN sudo pip install nudged \
    transforms3d \
    --break-system-packages




# Defines a workspace folder.
WORKDIR /home/$USER/ros_ws

CMD ["/bin/bash"]
