ARG ROS_DISTRO=kilted
FROM osrf/ros:${ROS_DISTRO}-desktop-full

ARG USERID=1000
ARG USER=admin
ARG ROS_DISTRO

######################
# 1) Environment
######################
ENV TERM=linux
ENV DEBIAN_FRONTEND=noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

######################
# 2) Install
######################
COPY docker/requirements.txt .
RUN apt-get update && apt-get install --no-install-recommends -y $(cat requirements.txt) && rm requirements.txt

######################
# 3) User
######################
RUN if id -u "$USER" >/dev/null 2>&1; then \
        usermod --uid "$USERID" "$USER"; \
    else \
        EXISTING_USER="$(getent passwd "$USERID" | cut -d: -f1 || true)"; \
        if [ -n "$EXISTING_USER" ]; then \
            usermod -l "$USER" "$EXISTING_USER"; \
            usermod -d "/home/$USER" -m "$USER"; \
        else \
            adduser --uid "$USERID" --gecos "admin" --disabled-password "$USER"; \
        fi; \
    fi \
    && usermod -a -G sudo,dialout,plugdev "$USER" \
    && (grep -qxF '%sudo ALL=(ALL) NOPASSWD:ALL' /etc/sudoers || echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers)
USER $USER

######################
# 4) Update
######################
RUN sudo apt-get update && sudo apt-get upgrade -y

######################
# 5) Gits and Sources
######################
RUN git config --global credential.helper store 
RUN git config --global user.email "admin@docker"
RUN git config --global user.name "admin"


RUN mkdir -p /home/$USER/ros_ws/src /home/$USER/ros_ws/build /home/$USER/ros_ws/install
WORKDIR /home/$USER/ros_ws/src
RUN git clone https://github.com/b-robotized/ads_vendor.git
RUN git clone https://github.com/b-robotized/beckhoff_ads_driver.git
RUN git clone https://github.com/orka375/tc_ros2_itf.git
RUN git clone https://github.com/b-robotized/open62541pp_vendor.git
RUN git clone https://github.com/b-robotized/ros2_opc_ua.git

WORKDIR /home/$USER/ros_ws
RUN rosdep install --from-paths src --ignore-src -r -y
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

######################
# 6) Bashrc
######################
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/$USER/.bashrc
RUN echo "source /home/$USER/ros_ws/install/setup.bash" >> /home/$USER/.bashrc
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /home/$USER/.bashrc
RUN echo "export ROS_DOMAIN_ID=1" >> /home/$USER/.bashrc
RUN echo "export QT_X11_NO_MITSHM=1" >> /home/$USER/.bashrc
RUN echo "export IGN_IP=127.0.0.1" >> /home/$USER/.bashrc
RUN echo "cd /home/$USER/ros_ws/src/tc_ros2_itf" >> /home/$USER/.bashrc
RUN echo "git pull" >> /home/$USER/.bashrc
RUN echo "cd ../.." >> /home/$USER/.bashrc

######################
# 7) Pip
######################
RUN sudo pip install nudged \
    transforms3d \
    psycopg2 \
    pyqt5 \
    --break-system-packages

######################
# 8) Workspace
######################
WORKDIR /home/$USER/ros_ws

CMD ["/bin/bash"]
